os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=clang++; export CXX=clang++; export CXXFLAGS=-stdlib=libc++; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-6; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install python3; export PATH="/c/Python38:/c/Python38/Scripts:$PATH"; python -m pip install --upgrade pip wheel; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
env:
  - DEBUG=true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - build-essential
      - libcairo2-dev
      - libpango1.0-dev
      - libjpeg-dev
      - libgif-dev
      - librsvg2-dev
  homebrew:
    packages:
      - cairo
      - librsvg
      - jpeg-turbo
script:
  - 'npm run test:package'
  - 'npm run test:unit'
  - 'npm run test:integration'
